# Generated by Django 5.2.17 on 2026-08-24 19:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Jméno / název firmy')),
                ('company_id', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='IČO')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('street', models.CharField(blank=True, max_length=160, verbose_name='Ulice a číslo')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Město')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PSČ')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
            ],
            options={
                'verbose_name': 'zákazník',
                'verbose_name_plural': 'zákazníci',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Název zakázky')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('status', models.CharField(choices=[('new', 'Nová'), ('in_progress', 'Probíhá'), ('waiting', 'Čeká'), ('done', 'Dokončena'), ('cancelled', 'Zrušena')], default='new', max_length=20, verbose_name='Stav')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Termín')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='records.customer', verbose_name='Zákazník')),
            ],
            options={
                'verbose_name': 'zakázka',
                'verbose_name_plural': 'zakázky',
                'ordering': ['-created_at'],
            },
        ),
    ]
