# Generated by Django 5.2.17 on 2026-08-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Aktivní'), ('inactive', 'Neaktivní'), ('archived', 'Archivovaný')], default='active', max_length=12, verbose_name='Stav'),
        ),
        migrations.AddField(
            model_name='job',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Důvod zrušení'),
        ),
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Dokončeno'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivováno'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Číslo zakázky'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Jméno a příjmení')),
                ('role', models.CharField(choices=[('executive', 'Jednatel'), ('ordering', 'Objednatel'), ('technical', 'Technický kontakt'), ('billing', 'Fakturace'), ('other', 'Jiná')], default='other', max_length=20, verbose_name='Funkce')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hlavní kontakt')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='records.customer', verbose_name='Zákazník')),
            ],
            options={
                'verbose_name': 'kontaktní osoba',
                'verbose_name_plural': 'kontaktní osoby',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='records.contact', verbose_name='Kontakt pro zakázku'),
        ),
    ]
