# Generated by Django 5.2.17 on 2026-08-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_fill_job_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Založení'), ('updated', 'Úprava'), ('transferred', 'Změna zákazníka'), ('archived', 'Archivace'), ('restored', 'Obnovení')], max_length=20, verbose_name='Akce')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Změny')),
                ('reason', models.TextField(blank=True, verbose_name='Důvod změny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Provedeno')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='records.job', verbose_name='Zakázka')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'změna zakázky',
                'verbose_name_plural': 'historie zakázek',
                'ordering': ['-created_at'],
            },
        ),
    ]
