# Generated by Django 5.2.17 on 2026-08-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_job_cancellation_reason_jobchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Založení zákazníka'), ('updated', 'Úprava zákazníka'), ('contact_created', 'Přidání kontaktu'), ('contact_updated', 'Úprava kontaktu'), ('contact_deleted', 'Odstranění kontaktu'), ('archived', 'Archivace zákazníka'), ('restored', 'Obnovení zákazníka')], max_length=24, verbose_name='Akce')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='Položka')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Změny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Provedeno')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='records.customer', verbose_name='Zákazník')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'změna zákazníka',
                'verbose_name_plural': 'historie zákazníků',
                'ordering': ['-created_at'],
            },
        ),
    ]
