# Generated by Django 5.2.17 on 2026-08-28 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_create_user_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobchange',
            name='action',
            field=models.CharField(choices=[('created', 'Založení'), ('updated', 'Úprava'), ('transferred', 'Změna zákazníka'), ('archived', 'Archivace'), ('restored', 'Obnovení'), ('invoice_created', 'Přidání faktury'), ('invoice_updated', 'Úprava faktury')], max_length=20, verbose_name='Akce'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Dodavatel')),
                ('supplier_company_id', models.CharField(blank=True, max_length=12, verbose_name='IČO dodavatele')),
                ('supplier_address', models.TextField(blank=True, verbose_name='Adresa dodavatele')),
                ('customer_header', models.TextField(blank=True, verbose_name='Odběratel / hlavička')),
                ('invoice_number', models.CharField(blank=True, max_length=80, verbose_name='Číslo faktury')),
                ('variable_symbol', models.CharField(blank=True, max_length=40, verbose_name='Variabilní symbol')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Datum vystavení')),
                ('taxable_date', models.DateField(blank=True, null=True, verbose_name='Datum zdanitelného plnění')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Datum splatnosti')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='Způsob platby')),
                ('items_text', models.TextField(blank=True, verbose_name='Práce a materiál')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Základ daně')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='DPH')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Celkem k úhradě')),
                ('currency', models.CharField(default='CZK', max_length=8, verbose_name='Měna')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('raw_text', models.TextField(blank=True, verbose_name='Původní rozpoznaný text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='records.job', verbose_name='Zakázka')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Naposledy upravil')),
            ],
            options={
                'verbose_name': 'faktura',
                'verbose_name_plural': 'faktury',
            },
        ),
    ]
