# Generated by Django 5.2.17 on 2026-08-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_jobchange_action_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'faktura',
                'verbose_name_plural': 'faktury',
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='records.job',
                verbose_name='Zakázka',
            ),
        ),
    ]
