# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_invoice_multiple_per_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobchange',
            name='action',
            field=models.CharField(
                choices=[
                    ('created', 'Založení'),
                    ('updated', 'Úprava'),
                    ('transferred', 'Změna zákazníka'),
                    ('archived', 'Archivace'),
                    ('restored', 'Obnovení'),
                    ('invoice_created', 'Přidání faktury'),
                    ('invoice_updated', 'Úprava faktury'),
                    ('invoice_deleted', 'Odstranění faktury'),
                ],
                max_length=20,
                verbose_name='Akce',
            ),
        ),
    ]
